server:
  port: 8083

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://192.168.56.11:3306/financier_transaction_db
    username: root
    password: root

management:
  endpoints:
    web:
      exposure:
        include: "*"

eurka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: users
    description: Users Service
    version: 1.0.0