server:
  port: 8083

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://192.168.56.11:3306/financier_transaction_db
    username: root
    password: root