server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.56.11:3306/userdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    profiles:
    active: prod
  rabbitmq:
    host: 192.168.56.11
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

#endpoints:
#  shutdown:
#    enabled: true

eurka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: users
    description: Users Service
    version: 1.0.0

build:
  version: 2.0

users:
  message: "This is default APIs"
  contactDetails:
    name: "Anurag Babal"
    email: "babalanurag2@gmail.com"