server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://192.168.56.11:3306/financier_user_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: users
    description: Users Service
    version: 1.0.0

build:
  version: 2.0

users:
  message: "This is default APIs"
  contactDetails:
    name: "Anurag Babal"
    email: "babalanurag2@gmail.com"